# our homepage url
baseURL: "https://cullmann.io/"

# cullmann.io website
title: "Ignorance is bliss..."

paginate: 5

theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true
    minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    vimeo:
        disabled: true

    twitter:
        disabled: true

    instagram:
        disabled: true

    youtube:
        disabled: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Ignorance is bliss..."
    author: Theme PaperMod
    # author: ["Me", "You"] # multiple authors

    defaultTheme: dark
    disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: false
    comments: false
    images: ["papermod-cover.png"]

    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Ignorance is bliss..."
        Content: >
            Welcome to Christoph Cullmann's personal web site.
    socialIcons:
        - name: github
          url: "https://github.com/christoph-cullmann"
        - name: gitlab
          url: "https://gitlab.com/cullmann"
        - name: reddit
          url: "https://www.reddit.com/user/ChristophCullmann"
        - name: twitter
          url: "https://twitter.com/ChrCullmann"
        - name: youtube
          url: "https://youtube.com/ChristophCullmann"
        - name: email
          url: "mailto:christoph@cullmann.io"

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        disableHLJS: true
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Posts
                  url: /posts/
                  weight: 5
                - name: Projects
                  url: /projects/
                  weight: 10
                - name: Academic
                  url: /academic/
                  weight: 15
                - name: Links
                  url: /links/
                  weight: 20
                - name: About
                  url: /about/
                  weight: 25
                - name: Impressum
                  url: /impressum/
                  weight: 30
