# our homepage url
baseURL = "https://cullmann.io/"

# cullmann.io website
title = "Ignorance is bliss..."

# theme hugo-coder
theme = "beautifulhugo"

# content == english, Impressum is german
languagecode = "en"
defaultcontentlanguage = "en"

# allow git
enableGitInfo = true

# nice urls
canonifyurls = true

# pygment settings
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# add info for crawlers
enableRobotsTXT = true

[outputs]
    # JSON for search
    home = ["HTML", "RSS", "JSON"]

[params]
    # we want to self-host stuff, no data leaks to google and co.
    selfHosted = true

    # Kate mascot
    logo = "images/christoph_avatar.png"

    dateFormat = "January 2, 2006"
    commit = true
    rss = false
    comments = false
    readingTime = true
    wordCount = false
    useHLJS = true
    socialShare = false
    showRelatedPosts = true


#
# links to my public profiles
#

[[params.social]]
    name = "E-Mail"
    icon = "fa fa-envelope"
    weight = 1
    url = "mailto:christoph@cullmann.io"

[[params.social]]
    name = "GitHub"
    icon = "fab fa-github"
    weight = 2
    url = "https://github.com/christoph-cullmann/"

[[params.social]]
    name = "GitLab"
    icon = "fab fa-gitlab"
    weight = 3
    url = "https://gitlab.com/cullmann"

[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 4
    url = "https://twitter.com/ChrCullmann/"

[[params.social]]
    name = "YouTube"
    icon = "fab fa-youtube"
    weight = 5
    url = "https://www.youtube.com/c/ChristophCullmann/"

[[params.social]]
    name = "amazon.de"
    icon = "fab fa-amazon"
    weight = 6
    url = "https://www.amazon.de/gp/profile/amzn1.account.AGWKWWFPCHLCW6E33CEFF7XKIHAQ"

#
# main menu
#

[menu]

  [[menu.main]]
    name = "BLOG"
    url = ""
    weight = 10

  [[menu.main]]
    identifier = "menu"
    name = "MORE"
    weight = 20

  [[menu.main]]
    parent = "menu"
    name = "Projects"
    url = "projects/"
    weight = 30

  [[menu.main]]
    parent = "menu"
    name = "Academic"
    url = "academic/"
    weight = 40

  [[menu.main]]
    parent = "menu"
    name = "Links"
    url = "links/"
    weight = 50

  [[menu.main]]
    parent = "menu"
    name = "Impressum"
    url = "impressum/"
    weight = 70

  [[menu.main]]
    name = "ABOUT"
    url = "about/"
    weight = 30

# maximal privacy
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
