# our homepage url
baseURL = "https://cullmann.io/"

# cullmann.io website
title = "cullmann.io"

# theme
theme = "hugo-coder"

# content == english, Impressum is german
languagecode = "en"
defaultcontentlanguage = "en"

# pagination
paginate = 20

# allow git
enableGitInfo = true

# nice urls
canonifyurls = true

# pygment settings
pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    # me
    author = "Christoph Cullmann"

    # what's this?
    description = "Christoph Cullmann's personal website"

    # some keywords
    keywords = "blog,developer,personal"

    # my profession
    info = "Software Engineer"

    # my cartoon variant ;=)
    avatarurl = "christoph.jpg"

    # ;=) how true
    footercontent = "Ignorance is bliss..."

    # nice footer
    hideCredits = true
    hideCopyright = false
    commit = "https://github.com/christoph-cullmann/cullmann.io/tree/"

    # no right to left
    rtl = false

    # Use inverted colors
    inverted = true

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

#
# links to my public profiles
#

[[params.social]]
    name = "GitHub"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/christoph-cullmann/"

[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/ChrCullmann/"

[[params.social]]
    name = "YouTube"
    icon = "fab fa-youtube"
    weight = 3
    url = "https://www.youtube.com/channel/UChxsQT-6tVSbEmfiPqMM1Jg"

[[params.social]]
    name = "amazon.de"
    icon = "fab fa-amazon"
    weight = 4
    url = "https://www.amazon.de/gp/profile/amzn1.account.AGWKWWFPCHLCW6E33CEFF7XKIHAQ"

#
# main menu
#

[menu]

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 10

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 20

  [[menu.main]]
    name = "Projects"
    url = "projects/"
    weight = 30

  [[menu.main]]
    name = "Academic"
    url = "academic/"
    weight = 40

  [[menu.main]]
    name = "Impressum"
    url = "impressum/"
    weight = 50
