# our homepage url
baseURL = "https://cullmann.io/"

# default content is in english
languageCode = "en-us"

# cullmann.io website
title = "cullmann.io"

# use hermit theme
theme = "hermit"

# hugo can use git
enableGitInfo = true

[author]
  name = "Christoph Cullmann"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  themeColor = "#494f5c"

  homeSubtitle = "Personal homepage of Christoph Cullmann."

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 20

  [[menu.main]]
    name = "Impressum"
    url = "impressum/"
    weight = 30
